{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe1c4653-a156-4733-920d-768f8e1eb694",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "file_path = 'Industry.xlsx - Prices.csv'\n",
    "industry_data = pd.read_csv(file_path)\n",
    "industry_data.head()\n",
    "\n",
    "class IndustryAnalysis:\n",
    "    def __init__(self, price_data):\n",
    "        self.price_data = price_data\n",
    "        self.price_data['Dates'] = pd.to_datetime(self.price_data['Dates'])\n",
    "    \n",
    "    def calc_moving_average(self, industry, window=5):\n",
    "        \"\"\"\n",
    "        Calculate weekly moving average for a given industry.\n",
    "        \n",
    "        :param industry: Name of the industry column.\n",
    "        :param window: Number of weeks to calculate moving average.\n",
    "        :return: DataFrame with moving averages.\n",
    "        \"\"\"\n",
    "        if industry not in self.price_data.columns:\n",
    "            raise ValueError(f\"Industry '{industry}' not found in data.\")\n",
    "        \n",
    "        moving_average = self.price_data.set_index('Dates')[industry].rolling(window=window).mean()\n",
    "        return moving_average\n",
    "\n",
    "    def calc_period_returns(self, industry):\n",
    "        \"\"\"\n",
    "        Calculate weekly returns for prices of a given industry.\n",
    "        \n",
    "        :param industry: Name of the industry column.\n",
    "        :return: DataFrame with weekly returns.\n",
    "        \"\"\"\n",
    "        if industry not in self.price_data.columns:\n",
    "            raise ValueError(f\"Industry '{industry}' not found in data.\")\n",
    "        \n",
    "        weekly_returns = self.price_data.set_index('Dates')[industry].pct_change(periods=1)\n",
    "        return weekly_returns\n",
    "\n",
    "    def events_plot(self, events, ax):\n",
    "        \"\"\"\n",
    "        Plot shaded rectangles for events with labels.\n",
    "\n",
    "        :param events: List of tuples with event start date, end date, and name.\n",
    "        :param ax: Matplotlib Axes object.\n",
    "        \"\"\"\n",
    "        for start, end, name in events:\n",
    "            ax.axvspan(pd.to_datetime(start), pd.to_datetime(end), color='gray', alpha=0.3, ymax=1)  # Set ymax to 1\n",
    "            mid_point = pd.to_datetime(start) + (pd.to_datetime(end) - pd.to_datetime(start)) / 2\n",
    "            ax.text(mid_point, ax.get_ylim()[1], name, horizontalalignment='center', verticalalignment='bottom', fontsize=8, rotation=45)\n",
    "\n",
    "    def series_plot(self, industry, plot_type='returns'):\n",
    "        \"\"\"\n",
    "        Plot periodic returns or moving average volume for a given industry.\n",
    "        \n",
    "        :param industry: Name of the industry.\n",
    "        :param plot_type: Type of plot ('returns' or 'moving_average').\n",
    "        \"\"\"\n",
    "        if plot_type not in ['returns', 'moving_average']:\n",
    "            raise ValueError(\"plot_type must be 'returns' or 'moving_average'.\")\n",
    "\n",
    "        fig, ax = plt.subplots(figsize=(12, 6))\n",
    "        \n",
    "        if plot_type == 'returns':\n",
    "            data = self.calc_period_returns(industry)\n",
    "            ax.plot(data.index, data, label=f'{industry} Weekly Returns', color='blue')\n",
    "        else:\n",
    "            data = self.calc_moving_average(industry)\n",
    "            ax.plot(data.index, data, label=f'{industry} Moving Average', color='green')\n",
    "        \n",
    "        ax.set_title(f'{industry} {plot_type.replace(\"_\", \" \").title()}')\n",
    "        ax.set_xlabel('Date')\n",
    "        ax.set_ylabel('Value')\n",
    "        ax.legend()\n",
    "        plt.show()\n",
    "\n",
    "    def plot_all(self, industry, events, plot_type='returns'):\n",
    "        \"\"\"\n",
    "        Plot all data, including events overlay.\n",
    "\n",
    "        :param industry: Name of the industry.\n",
    "        :param events: List of tuples with event start and end dates.\n",
    "        :param plot_type: Type of plot ('returns' or 'moving_average').\n",
    "        \"\"\"\n",
    "        fig, ax = plt.subplots(figsize=(12, 6))\n",
    "        \n",
    "        if plot_type == 'returns':\n",
    "            data = self.calc_period_returns(industry)\n",
    "            max_value = data.max()\n",
    "            ax.plot(data.index, data, label=f'{industry} Weekly Returns', color='blue')\n",
    "        else:\n",
    "            data = self.calc_moving_average(industry)\n",
    "            max_value = data.max()\n",
    "            ax.plot(data.index, data, label=f'{industry} Moving Average', color='green')\n",
    "        \n",
    "        self.events_plot(events, ax)\n",
    "\n",
    "        ax.set_title(f'{industry} {plot_type.replace(\"_\", \" \").title()} with Events')\n",
    "        ax.set_xlabel('Date')\n",
    "        ax.set_ylabel('Value')\n",
    "        ax.legend()\n",
    "        plt.show()\n",
    "\n",
    "        \n",
    "        updated_events = [('2000-01-01', '2000-05-01', 'Event 1'), ('2001-05-01', '2001-06-01', 'Event 2')]\n",
    "\n",
    "industry_analysis = IndustryAnalysis(industry_data)\n",
    "industry_analysis.series_plot('Healthcare', plot_type='returns')\n",
    "industry_analysis.plot_all('Financials', updated_events, plot_type='returns')\n",
    "industry_analysis.plot_all('Financials', updated_events, plot_type='moving_average')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
